name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Installer Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les outils
        run: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Préparer Capacitor
        run: |
          npx cap sync android

      - name: Créer Android
        run: |
          npx cap add android

      - name: Compiler APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Publier APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-Gestion-Immobiliere
          path: android/app/build/outputs/apk/debug/app-debug.apk
