name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Ajouter Android
        run: |
          npx cap add android

      - name: Synchroniser Capacitor
        run: |
          npx cap sync android

      - name: Compiler APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Récupérer APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-Gestion-Immobiliere
          path: android/app/build/outputs/apk/debug/app-debug.apk
